dist: bionic

cache: pip

language: python
python:
  - "3.7"

services:
  - postgresql

addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10-postgis-2.5
    
before_script:
  - psql -U postgres -c "CREATE EXTENSION postgis"
  - psql -U postgres -c "CREATE ROLE bornhack WITH SUPERUSER LOGIN PASSWORD 'bornhack';"

install:
  - pip install -r src/requirements/dev.txt

script:
  - cp src/bornhack/environment_settings.py.dist.dev src/bornhack/environment_settings.py
  - coverage run --source src/ src/manage.py test src/

after_success:
  - codecov
