dist: bionic

cache: pip

language: python
python:
  - "3.7"

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-10-postgis-2.5

install:
  - pip install -r src/requirements/dev.txt

before_script:
  - psql -c "CREATE ROLE bornhack WITH SUPERUSER LOGIN PASSWORD 'bornhack';"

script:
  - cp src/bornhack/environment_settings.py.dist.dev src/bornhack/environment_settings.py
  - coverage run --source src/ src/manage.py test src/

after_success:
  - codecov
